### ISSUE TITLE
運行報錯 TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ThekingMX1998** [ArsFy/katonei_bot#3]
所有環境都已正確安裝并已配置完全 config.json 

鍵入 node main.js 運行后報錯

### 未對其他文件進行修改

**下方為運行結果:**

```
root@ubuntu:~/katonei_bot# node main.js
Start bot...
/root/katonei_bot/main.js:57
                    switch (result[0].type) {
                                      ^

TypeError: Cannot read property 'type' of undefined
    at /root/katonei_bot/main.js:57:39
    at /root/katonei_bot/node_modules/mongodb/lib/utils.js:424:9
    at /root/katonei_bot/node_modules/mongodb/lib/cursor/abstract_cursor.js:257:32
    at next (/root/katonei_bot/node_modules/mongodb/lib/cursor/abstract_cursor.js:497:16)
    at /root/katonei_bot/node_modules/mongodb/lib/cursor/abstract_cursor.js:511:20
    at /root/katonei_bot/node_modules/mongodb/lib/cursor/abstract_cursor.js:461:66
    at /root/katonei_bot/node_modules/mongodb/lib/utils.js:424:9
    at completeEndSession (/root/katonei_bot/node_modules/mongodb/lib/sessions.js:154:17)
    at /root/katonei_bot/node_modules/mongodb/lib/sessions.js:166:13
    at maybePromise (/root/katonei_bot/node_modules/mongodb/lib/utils.js:410:5)
    at ClientSession.endSession (/root/katonei_bot/node_modules/mongodb/lib/sessions.js:133:41)
    at cleanupCursor (/root/katonei_bot/node_modules/mongodb/lib/cursor/abstract_cursor.js:563:32)
    at /root/katonei_bot/node_modules/mongodb/lib/cursor/abstract_cursor.js:461:24
    at /root/katonei_bot/node_modules/mongodb/lib/cursor/aggregation_cursor.js:50:13
    at /root/katonei_bot/node_modules/mongodb/lib/utils.js:424:9
    at /root/katonei_bot/node_modules/mongodb/lib/operations/execute_operation.js:73:17
    at /root/katonei_bot/node_modules/mongodb/lib/operations/execute_operation.js:178:21
    at /root/katonei_bot/node_modules/mongodb/lib/cmap/connection_pool.js:277:25
    at /root/katonei_bot/node_modules/mongodb/lib/sdam/server.js:212:17
    at handleOperationResult (/root/katonei_bot/node_modules/mongodb/lib/sdam/server.js:335:20)
    at Connection.onMessage (/root/katonei_bot/node_modules/mongodb/lib/cmap/connection.js:222:9)
    at MessageStream.<anonymous> (/root/katonei_bot/node_modules/mongodb/lib/cmap/connection.js:63:60)
```

**Comment by arsfy** [comment]
請問有無添加過圖片？

**Comment by ThekingMX1998** [comment]
> 請問有無添加過圖片？

沒有

**Comment by ThekingMX1998** [comment]
> 請問有無添加過圖片？

是需要在 photos 檔案夾裡手動添加嗎

**Comment by arsfy** [comment]
> > 請問有無添加過圖片？
> 
> 是需要在 photos 檔案夾裡手動添加嗎

README 有添加命令教學 (`/addpixiv`, `/addphoto`)
