### ISSUE TITLE
错误，求解题

### ISSUE THREAD

**Issue by ghost** [ArsFy/katonei_bot#6]
/katonei_bot/node_modules/whatwg-url/lib/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/katonei_bot/node_modules/whatwg-url/lib/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/katonei_bot/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

运行node main.js如图
config已填写好了

**Comment by arsfy** [comment]
請問nodejs版本？

**Comment by ghost** [comment]
我是使用apt install nodejs安装的
不知道什么版本，待我谷歌

**Comment by ghost** [comment]
懂了，是因为他安装的是10
我在装14

**Comment by arsfy** [comment]
一般來講這個問題是因為版本過低
