### ISSUE TITLE
無法添加 Pixiv提示敏感內容的圖片

### ISSUE THREAD

**Issue by ThekingMX1998** [ArsFy/katonei_bot#7]
**操作系統:** Ubuntu 20.04.5 LTS aarch64

**node版本:** v14.21.2

已正確配置 config.json , 且cookie有效

-------------------------------------------------------------------------------------------------------------------
**錯誤log如下:**

```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:170:3)
    at Object.urlParse [as parse] (url.js:157:13)
    at dispatchHttpRequest (/var/lib/GFNKB/node_modules/axios/lib/adapters/http.js:124:22)
    at new Promise (<anonymous>)
    at httpAdapter (/var/lib/GFNKB/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/var/lib/GFNKB/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/var/lib/GFNKB/node_modules/axios/lib/core/Axios.js:108:15)
    at wrap (/var/lib/GFNKB/node_modules/axios/lib/helpers/bind.js:9:15)
    at /var/lib/GFNKB/getPixiv.js:29:34
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Telegram客戶端内顯示:**

`@chenjranyang 載入圖像時發生錯誤！目標可能不存在或伺服器故障`

**Comment by arsfy** [comment]
Pixiv 的新反爬機制，我需要花時間解決

**Comment by ThekingMX1998** [comment]
好的 感謝答復

**Comment by arsfy** [comment]
因爲這一年都好忙，但是我想起來並解決了這個問題，我更新了這個專案並新增了新的功能，希望你還需要它

**Comment by ThekingMX1998** [comment]
THX 非常感謝
